### ISSUE TITLE
Push notification will not work in background if this plugin is installed. 

### ISSUE THREAD

**Issue by scripterkaran** [Azure/azure-mobile-engagement-cordova#10]
cdvamaz-test will track the "didreceiveremotenotification" and it fails, as app init function is not called.

**Comment by piyushjo** [comment]
Hello, apologies for not looking at this earlier. Could you please provide more details? What is the impact? Are the notifications not being received? Have you tried the latest SDK with enhanced logging and iOS 9 support? Thank you.
