### ISSUE TITLE
Working example with real connection string

### ISSUE THREAD

**Issue by tezqa** [Azure/azure-mobile-engagement-cordova#11]
I did not succeed to receive in app notifications in my iOS app. All works fine with the v 1.0.
Could you add a working example with a real connection string?
Do i have to escape some characters (= ;) or something else?

**Comment by piyushjo** [comment]
Which SDK version are you using? We have an updated iOS Cordova SDK version which works for iOS 9 also and with better logging capability - https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-engagement. There is another basic get started tutorial here - https://azure.microsoft.com/en-us/documentation/articles/mobile-engagement-cordova-get-started/
