### ISSUE TITLE
Exception: Cordova run

### ISSUE THREAD

**Issue by Devilox** [Azure/azure-mobile-engagement-cordova#13]
Hello,

I have a problem when i want run my app on cordova:

Running command: /srv/www/ionic/app/platforms/android/cordova/run --debug --device
Running: /srv/www/ionic/app/platforms/android/gradlew cdvBuildDebug -b /srv/www/ionic/app/platforms/android/build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.123 secs

/srv/www/ionic/app/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /srv/www/ionic/app/platforms/android/gradlew with args: cdvBuildDebug,-b,/srv/www/ionic/app/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
ERROR running one or more of the platforms: Error: /srv/www/ionic/app/platforms/android/cordova/run: Command failed with exit code 8
You may not have the required environment or OS to run this project

--------------
plugin version: 2.2.0
cordova: 5.3.4
crosswalk: 1.4.0

Thanks for help

**Comment by ogoguel** [comment]
Try adding the Android Support Library in the SDK Manager
In Android Studio, can be found in Tools/Android/SDK Manager/SDK Tools

Cf.
http://stackoverflow.com/questions/19958213/how-to-add-android-support-repository-to-android-studio



2016-01-15 17:07 GMT+01:00 Devilox <notifications@github.com>:

> Hello,
>
> I have a problem when i want run my app on cordova:
>
> Running command: /srv/www/ionic/app/platforms/android/cordova/run --debug
> --device
> Running: /srv/www/ionic/app/platforms/android/gradlew cdvBuildDebug -b
> /srv/www/ionic/app/platforms/android/build.gradle -PcdvBuildArch=arm
> -Dorg.gradle.daemon=true
>
> FAILURE: Build failed with an exception.
>
>    -
>
>    What went wrong:
>    A problem occurred configuring root project 'android'.
>
>    Could not resolve all dependencies for configuration ':_debugCompile'.
>    Could not find any version that matches
>    com.android.support:support-v4:+.
>    Searched in the following locations:
>
>    https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
>    https://repo1.maven.org/maven2/com/android/support/support-v4/
>    Required by:
>    :android:unspecified
>
>    -
>
>    Try:
>    Run with --stacktrace option to get the stack trace. Run with --info
>    or --debug option to get more log output.
>
> BUILD FAILED
>
> Total time: 7.123 secs
>
> /srv/www/ionic/app/platforms/android/cordova/node_modules/q/q.js:126
> throw e;
> ^
> Error code 1 for command: /srv/www/ionic/app/platforms/android/gradlew
> with args:
> cdvBuildDebug,-b,/srv/www/ionic/app/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
> ERROR running one or more of the platforms: Error:
> /srv/www/ionic/app/platforms/android/cordova/run: Command failed with exit
> code 8
> You may not have the required environment or OS to run this project
> ------------------------------
>
> plugin version: 2.2.0
> cordova: 5.3.4
> crosswalk: 1.4.0
>
> Thanks for help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-mobile-engagement-cordova/issues/13>.
>



-- 
ıllıllı ɹǝ!ʌ!ןo ıllıllı

**Comment by Devilox** [comment]
I'm not android developer, i don't use Android Studio but i have already android support library and i'm already used differents cordova plugins without this problem :(
What are the minimum versions can we use why the plugin ? Android and Cordova ?
Before, i used capptain plugin : com.microsoft.capptain - version 1.0.2 and it worked perfectly

**Comment by ogoguel** [comment]
In the Capptain flavor of the plugin, the Android support library was embedded within the plugin (cf. https://github.com/Azure/azure-mobile-engagement-capptain-cordova/tree/master/src/android/libs) but this could lead to conflict if other plugins were also using it.  This is why it has been replaced by a reference/dependency in the AZME plugin (the Capptain plugin being deprecated, it has not been updated with that modification!).

However, to resolve that dependency, the "Android Support Repository" must be present within your Android SDK : even if you're not an Android Developer, you had to install the Android SDK to be able to build for the Android platform, but the "Android Support Repository" is not installed by default.

To manually install the "Android Support Repository" (and not the  "Android Support Library" as I wrongly wrote in y previous reply), please check http://developer.android.com/tools/support-library/setup.html.

Hope it helps!

PS: The minimum required version for the plugin is Cordova 5.2.0 (but it is checked during the plugin installation), and Android version 16 (as requested by Cordova).

**Comment by Devilox** [comment]
Yes ! Its works thx @ogoguel. I manually installed "Android Support Repository". We use Ansible to provide machine with Android SDK and it missing parameter "extra-google-m2repository,extra-android-m2repository"
