### ISSUE TITLE
add support for other events : sessionEvent, sessionErrorEvent, error ...

### ISSUE THREAD

**Issue by dcz-switcher** [Azure/azure-mobile-engagement-cordova#14]
Hello,

Thanks for this great plugin, easy to install and well documented.

Will you plan to add other "events" support like : 
sessionEvent,
sessionErrorEvent,
jobEvent,
...

regards

**Comment by piyushjo** [comment]
Yes we do plan to update it soon to address these gaps. Look out for an update within the next couple of weeks.
