### ISSUE TITLE
android : session stay alive when app paused

### ISSUE THREAD

**Issue by dcz-switcher** [Azure/azure-mobile-engagement-cordova#17]
Hello,

My need : i just want to see in Monitor, my session activiy
So, I launch my app and start new Activity --> I can see 1 active session in Monitor
then I stop activity --> the session's counter pass to 0

Now, I start activity (session's counter = 1)
and kill my app --> session's counter stay 1

So I restart my app, start and stop activity --> session = 0

To force session ending, I add eventListener on "pause" event and stopActivity manually
```
document.addEventListener("pause", function (){
    console.log("onPause event fired");
    AzureEngagement.endActivity(
        function () { console.log('endActivity success');},
        function () { console.log('endActivity failed');}
   );
}, false);
```

Then, I start activity --> counter = 1
and kill app
    I see in LogCat the onPause code, but session stay 1

In LogCat : 
```
03-24 10:37:33.103: I/chromium(32458): [INFO:CONSOLE(32)] "onPause event fired", source: file:///android_asset/www/js/app.js (32)
03-24 10:37:33.104: I/cdvazme-test(32458): execute: endActivity w/ []
03-24 10:37:33.108: I/chromium(32458): [INFO:CONSOLE(35)] "endActivity success", source: file:///android_asset/www/js/app.js (35)
03-24 10:37:33.146: D/engagement-test(32532): io.cordova.pocAzme: Session will be idle in 1000 ms
03-24 10:37:33.146: D/engagement-test(32532): io.cordova.pocAzme: Session will be ended in 10000 ms
03-24 10:37:33.149: E/engagement-test(32532): io.cordova.pocAzme: Activity already ended (session is idle), this is not an error if you see this when leaving a tab activity.
```

**Comment by ogoguel** [comment]
You don't need to override the pause event in your javascript code to end the current activity: it is already done in the Java plugin (cf. onPause/onResume in AZME.java)

Actually, when an app is being killed (and not just pushed in the background), not event at all is being received, which explains why the session/activity cannot be properly ended. However, there's a timeout in the persistent Engagement agent that will end the session  after a minute or so

**Comment by dcz-switcher** [comment]
Thanks for the explanation.
It's ok for me, after been paused, activity is stopped automatically if I don't kill app immediately

**Comment by greybax** [comment]
I'm not sure that this issue was fixed. In my case when app was killed I can see my Session about 30 minutes after that in monitor. I've created also task https://github.com/Azure/azure-mobile-engagement-cordova/issues/52 for this issue
