### ISSUE TITLE
onOpenURL only call when app is not alive ? (android)

### ISSUE THREAD

**Issue by dcz-switcher** [Azure/azure-mobile-engagement-cordova#18]
Sorry, for this question.

I play with push notification out of app

If I kill my application and send push notification with action url = 
```
poc_azme://hello
```

My app is waking up and I can see in console.log the url 'hello'

But if I send push and myApp is already launched (background or not), I receive push but onOpenURL is not called even if the app is resume

Is it the normal behavior ?

regards

**Comment by ogoguel** [comment]
Nope : it should work even when the app is already launched, and you should see something like :

`03-26 00:51:57.302 15674 15674 D engagement-plugin: intent handleOpenURL=myapp://shop`

Could you attached your log file ?

**Comment by dcz-switcher** [comment]
Ok, I do many tests today and confirm that the event onOpenURL is not launch if app is already open (in background or not)

Here is an extract of my log cat
When app is already launch :
```
03-29 18:29:53.570: I/ActivityManager(825): START u0 {act=android.intent.action.VIEW dat=poc_azme://hello flg=0x10000000 cmp=io.cordova.pocAzme/.MainActivity} from uid 10414 on display 0
03-29 18:29:53.646: D/cr_Ime(5305): [ImeAdapter.java:140] onCreateInputConnection returns null.
03-29 18:29:53.649: I/cdvazme-test(5305): execute: checkRedirect w/ ["url"]
03-29 18:29:53.656: I/Keyboard.Facilitator(1967): onFinishInput()
03-29 18:29:53.664: I/chromium(5305): [INFO:CONSOLE(48)] "[DCZ] onresume", source: file:///android_asset/www/js/app.js (48)
03-29 18:29:53.704: I/LaunchCheckinHandler(825): Displayed io.cordova.pocAzme/.MainActivity,wp,wa,135
```

When app is not launch
```
03-29 18:29:32.286: I/ActivityManager(825): START u0 {act=android.intent.action.VIEW dat=poc_azme://hello flg=0x10000000 cmp=io.cordova.pocAzme/.MainActivity} from uid 10414 on display 0
03-29 18:29:32.809: I/engagement-test(5325): io.cordova.pocAzme: AppInfo triggered: {"CDVAZMEVersion":"2.2.0"}
03-29 18:29:33.033: D/cr_Ime(5305): [ImeAdapter.java:140] onCreateInputConnection returns null.
03-29 18:29:33.037: I/Keyboard.Facilitator(1967): onFinishInput()
03-29 18:29:33.047: D/cr_Ime(5305): [ImeAdapter.java:140] onCreateInputConnection returns null.
03-29 18:29:33.065: I/LaunchCheckinHandler(825): Displayed io.cordova.pocAzme/.MainActivity,wp,ca,728
03-29 18:29:33.065: I/ActivityManager(825): Displayed io.cordova.pocAzme/.MainActivity: +728ms
03-29 18:29:33.194: D/JsMessageQueue(5305): Set native->JS mode to OnlineEventsBridgeMode
03-29 18:29:33.369: V/engagement-test(5325): io.cordova.pocAzme: Connection: Sent: appInfo
03-29 18:29:34.034: I/chromium(5305): [INFO:CONSOLE(20)] "[DCZ] - device ready", source: file:///android_asset/www/js/app.js (20)
03-29 18:29:34.043: I/cdvazme-test(5305): execute: getStatus w/ []
03-29 18:29:34.048: I/cdvazme-test(5305): execute: checkRedirect w/ ["url"]
03-29 18:29:34.059: I/chromium(5305): [INFO:CONSOLE(36)] "[DCZ] onOpenURL url=poc_azme://hello", source: file:///android_asset/www/js/app.js (36)
```

**Comment by ogoguel** [comment]
There's indeed a bug : if you create a notification with an announcement, the onOpenURL is properly called (my test case) , but if it is an notification only push (with no additional view), it is not called if the app is already running/in the background (your case).
I'm working on a fix.

**Comment by ogoguel** [comment]
Fixed in v3.0.1 : https://github.com/Azure/azure-mobile-engagement-cordova/pull/16
(warning, there are some minor API breaking changes)

**Comment by ogoguel** [comment]
Version 3.0.1 has been merged into the master branch : @dcz-switcher, can you confirm it solves your issue?

**Comment by dcz-switcher** [comment]
it works !
thanks for your reactivity and for the other improvements (sendSessionEvent ...)
