### ISSUE TITLE
[ios] deviceID change between 2 builds

### ISSUE THREAD

**Issue by dcz-switcher** [Azure/azure-mobile-engagement-cordova#20]
Hello,

On iOS, every time I build and deploy my app on a real device, the device ID change
note, on Android, the deviceID is always the same

Is it the normal behavior ?

bests regards

**Comment by ogoguel** [comment]
Nope : the DeviceId should remain the same as long as the app is not deleted from the device.

It works fine on my sample app, so I'm suspecting a conflict with another plugin that could erase the application localstorage/NSUserDefaults (where the device id is being stored) : could you confirm which platform you are using (cordova platform list), and which plugins you have installed (cordova plugin list) so I can try to reproduce your issue ?

**Comment by dcz-switcher** [comment]
Here is the platform and plugin list :
Installed platforms: ios 3.9.2
Available platforms: amazon-fireos, android, blackberry10, browser, firefoxos, osx, webos

cordova-plugin-ms-azure-mobile-engagement 3.0.1 "Azure Mobile Engagement"
cordova-plugin-whitelist 1.2.1 "Whitelist"

But, I confirm that the device ID change only if I uninstall the app before build it
So, if I understand, on android device ID is always the same even I uninstall the app 
but on iOS, the device ID change between two installations.

Is it right ?

**Comment by ogoguel** [comment]
Yes, but it is a bit more complex than that ;)

The device ID is based on the IDFV (Identifier for Vendor), which is resetted when the last application of the vendor is being uninstalled. Hence, if it is the only app from this vendor on the device, the device ID will change every time the app is being uninstalled.

But if you have multiple apps from the same vendor, the device ID should remain the same as long there's always at least one app installed from that vendor

**Comment by dcz-switcher** [comment]
thanks for the explanation
