### ISSUE TITLE
Can't open another screen on app when a user clicks on the push notification

### ISSUE THREAD

**Issue by WennderSantos** [Azure/azure-mobile-engagement-cordova#27]
I am using IONIC framework with the azure mobile engagement plugin for cordova based project.

All the features (in-app message, push, campaing, analytics) are working fine. But, I want to send a push notifiction that when the users click on it they jump to another screen.

For example, I want the users jump to screen "promo" when they click on the push notification.

How I have to pass the parameter in that field on azure mobile engagement portal? I tried with these values ('/promo', '#/promo', 'promo'), but didn't work.

This is the filed
![asdf](https://cloud.githubusercontent.com/assets/7007105/17236453/787f376a-551f-11e6-825f-86c791642102.PNG)

**Comment by ogoguel** [comment]
The sdk is framework agnostic, hence you need to write your own function related to open a page within the ionic framework. 

To do that :
1) install the plugin with a AZME_REDIRECT_URL such as "myapp"
2) in the azme portal, use the redirect url : myapp://promo
3) set an openurlhandler using the EngagementReach.initialize function
4) when the handler is being called, the target url will be passed as a parameter, and from there you should be able to write your ionic specific redirection code, something like $state.go(targetPage). 

Hope this will be enough to unblock you :if not, let me know and I will post a more complete ionic framework sample

Cheers
Olivier

**Comment by WennderSantos** [comment]
Hey @ogoguel , thanks for the help.

I tried this way but didn't work, nothing happened after I clicked on the push notification. If I use another url like www.wenndersantos.net it works.

This my code:
`Engagement.initializeReach(
        // on OpenUrl  
        function (_url) {
          $state.go('promo');
        });
`
This is my config.xml:
`<plugin name="cordova-plugin-ms-azure-mobile-engagement" spec="~3.0.1">
        <variable name="AZME_ANDROID_CONNECTION_STRING" value=MY_CONN_STRING" />
        <variable name="AZME_ANDROID_GOOGLE_PROJECT_NUMBER" value="MY_PROJECT_NUMBER" />
        <variable name="AZME_ACTION_URL" value="AzureMobileEngagement" />
        <variable name="AZME_ENABLE_PLUGIN_LOG" value="true" />
        <variable name="AZME_ENABLE_NATIVE_LOG" value="true" />
        <variable name="AZME_ANDROID_REACH_ICON" value="icon" />
    </plugin>`

In the azme portal i used the url **AzureMobileEngagement://promo**

Any idea?

**Comment by opteameo** [comment]
Your settings seems corrects... 

My only hint is that in $state.go("promo"), "promo"' is the name of the url, not the name of the state associated to this url.  Can you share your .state() definitions to confirm/infirm this hypothesis ?

(You could use an url, but it is a bit tricky and there are a lot of discussions about it : 
cf. http://stackoverflow.com/questions/30791607/angular-ui-router-go-to-url)

**Comment by WennderSantos** [comment]
Hey @opteameo 
Here is:
` .state('promo', {
        url: '/promo',
        templateUrl: 'templates/promo.html',
        controller: 'PromoCtrl'
      }`

It seems that my callback
 `function (_url) { $state.go('promo'); }` 
its never called. I tried debug, but the code never stop there.

**Comment by ogoguel** [comment]
OK, so 'promo' is a proper state name, so it should have worked!

But as the callback is never called, the issue is obviously related to the notifications not being received at all : can you share your application log to help me understand where the problem could come from ?

**Comment by WennderSantos** [comment]
An important information that I forgot to say and maybe helps, I am testing on an android device.
Even when I use the url **http://wenndersantos.net** the callback isn't called, but the site opens.

@ogoguel what log do you want?

**Comment by ogoguel** [comment]
If the callback is not called but an url with http:// is properly opened, it means a) the push is received, b) the scheme AzureMobileEngagement:// is not tied to the application.
Normally, the plugin should add the follow lines in your manifest :
```
<intent-filter>
 <action android:name="android.intent.action.VIEW"/> 
 <category android:name="android.intent.category.DEFAULT"/>
 <category android:name="android.intent.category.BROWSABLE"/>
 <data android:scheme="$AZME_ACTION_URL"/>
</intent-filter>
```
Please share your AndroidManifest.xml file as well as the Android logs (using adb logcat).

**Comment by WennderSantos** [comment]
Guys, I found the problem! It's me :(

After last answer of @ogoguel , I went see my manifest and the scheme was thus
`<data android:scheme="$AZME_ACTION_URL"/>`

I tried reinstalling the plugin several times to see what was happening. I was trying to install that way

`cordova plugin add cordova-plugin-ms-azure-mobile-engagement --variable AZME_ANDROID_CONNECTION_STRING="Endpoint=fs-collection-app.device.mobileengagement.windows.net;SdkKey=b041d02976ccf980069b9a376893787d;AppId=cud000153" --variable AZME_ANDROID_GOOGLE_PROJECT_NUMBER="141666565087" AZME_ACTION_URL="azme"`

Can you see the mistake? I didn't put the **--variable** before **AZME_ACTION_URL**. after I installed the right way, it worked.

I just had to remove the "azme://' in the url before the state.go. In a ugly way, something like that:
` $state.go(url.substring(url.indexOf('://') + 3));`

Thanks so much for the help and sorry for my mistake.
