### ISSUE TITLE
Confirm how initializeReach works

### ISSUE THREAD

**Issue by dcz-switcher** [Azure/azure-mobile-engagement-cordova#28]
Hello,

I just want to have confirmation how initializeReach works.
This function allow to manage Reach calls. On iOS, call this function prompt the user to allow notification from our app.

But, can you confirm that we have to call this function every times the app start ?

If so, is there a way to detect if the user have already allow or not for push, to prevent call it at the first start of the app ?

If not, I suppose that I have to store this state in my app

regards

**Comment by piyushjo** [comment]
I would assume that the IOS platform should automatically take care of this i.e. you can initiatizeReach on app start. First time, the platform asks user for permission. From second time onwards, the iOS platform must be storing this state and not prompting again. Is this not what you are seeing?

**Comment by dcz-switcher** [comment]
Thanks for your answer.
I want to follow the doc's advice for iOS platform : 

> on IOS, this call will ask the user to autorize push notifications for your application, so it is recommended to trigger that call at the proper time (ie: once the users are engaged into your application)

I want to understand if initializeReach() have to be called each time the app starts

I suppose yes because if I update the onOpenURL() function and because this function is a param of initializeReach(), it must be called.

am I right ?

**Comment by ogoguel** [comment]
Yes, initializeReach() has to be called each time the app starts to be able to receive the push (through the onOpenURL() callback)
