### ISSUE TITLE
iOS 10 issue

### ISSUE THREAD

**Issue by dcz-switcher** [Azure/azure-mobile-engagement-cordova#30]
Hello,

This morning, we receive an email about an iOS 10 issue.

How apply it with the Cordova plugin ?

"If you have an iOS app on Azure Mobile Engagement i.e. you have integrated the Azure Mobile Engagement (AzME) iOS SDK then read on about an iOS 10 issue which may impact you.
 
Who is impacted
AzME SDK is safe to include with an app running on iOS 10. There is no crash or error just by having the SDK present. However if you are sending an out-of-app notification or an anytime notification then the app users will see unexpected behavior when they click on the out-of-app notification displayed in the notification center unless the following code is present in the app:
 
- (void)application:(UIApplication*)application didReceiveRemoteNotification:(NSDictionary*)userInfo
{
  [[EngagementAgent shared] applicationDidReceiveRemoteNotification:userInfo fetchCompletionHandler:nil];
}
 
[Note that this code was only required for iOS6 compatibility so it is not expected to be present on apps targeting iOS7 and above] ..."

**Comment by piyushjo** [comment]
We will update the Cordova plugin soon to wrap around this latest iOS SDK.

**Comment by piyushjo** [comment]
The Cordova plugin has been updated to wrap around the native iOS SDK updated for iOS 10. There are no breaking changes or API changes at the Cordova layer.
