### ISSUE TITLE
iOS : feature proposal : add method to check if notification is already enable for the app

### ISSUE THREAD

**Issue by dcz-switcher** [Azure/azure-mobile-engagement-cordova#32]
Hello,

I need to check if notification is allowed for my app.
My need is to display a popup before call initializeReach to be sure that the user's answer will be yes
The popup explains why I want to send push notifications

But because my app is already on the store and some people have already answered, I must check if notification setting is not already defined for my app before display my popup

So, I plan to add this method.

Will you accept pull request for this ?

**Comment by ogoguel** [comment]
This would make sense to add this kind of information in the getStatus() - not to break the API. Will add tha

**Comment by piyushjo** [comment]
Hi @dcz-switcher , we plan to add the API through #33. Let us know what you think of it.

**Comment by dcz-switcher** [comment]
Hi,

Thanks for your reactivity

the param's comment says : "if the user has already accepted to receive notifications"

But what if we don't already ask for permission ?
variable is set to null or false ?

In my case I wan't to know if we already (in previous version of our app) ask for permission (the answer is not important here)

If we already ask, we can call initializeReach() to manage push with urlscheme
=> if user have rejected notification, nothing append

if we dont' already ask for permission, we can wait and ask it later in our app when the user is engaged (and display a popup before native one which explain why we wan't it)

I hope my answer is understandable, my english is not great ;-)

**Comment by ogoguel** [comment]
notificationGranted will be set to true only if the user has accepted it (and false for all the other case), but we can't say if the permission popup has been presented to him.

normally, that's up to the app developer to know whether the user has already been engaged or not.
