### ISSUE TITLE
Tests crash the app on Windows

### ISSUE THREAD

**Issue by alsorokin** [Azure/azure-mobile-engagement-cordova#37]
Hi,
It's me again, and it's another crash on Windows 😈 

Steps to repro:
```
cordova create foo
cd foo
cordova platform add windows
cordova plugin add ../azure-mobile-engagement-cordova --variable AZME_WINDOWS_CONNECTION_STRING=Endpoint=0;AppId=0;SdkKey=0
cordova plugin add ../azure-mobile-engagement-cordova/tests
cordova plugin add cordova-plugin-test-framework
```
change content tag in config.xml to:
`<content src="cdvtests/index.html" />`

`cordova run`

The app starts, then promptly crashes.
The `Microsoft-Windows-AppHost/Admin` event log contains the following exception details:
```
App <io.cordova.hellocordova> crashed with an unhandled Javascript exception. App details are as follows: Display Name:<HelloCordova>, AppUserModelId: <io.cordova.hellocordova_h35559jr9hy9m!io.cordova.hellocordova> Package Identity:<io.cordova.hellocordova_1.0.0.0_neutral__h35559jr9hy9m> PID:<11848>. The details of the JavaScript exception are as follows Exception Name:<Generic error>, Description:<The system cannot locate the resource specified.
>, HTML Document Path:</www/cdvtests/index.html>, Source File Name:<ms-appx://io.cordova.hellocordova/www/plugins/cordova-plugin-ms-azure-mobile-engagement/src/winjs/EngagementProxy.js>, Source Line Number:<27>, Source Column Number:<1>, and Stack Trace: ms-appx://io.cordova.hellocordova/www/plugins/cordova-plugin-ms-azure-mobile-engagement/src/winjs/EngagementProxy.js:27:1           Anonymous function(object, object, object)
           ms-appx://io.cordova.hellocordova/www/cordova.js:53:9           build(object)
           ms-appx://io.cordova.hellocordova/www/cordova.js:68:17           require(string)
           ms-appx://io.cordova.hellocordova/www/cordova.js:49:17           localRequire(string)
           ms-appx://io.cordova.hellocordova/www/cordova.js:1345:9           exports.mapModules(object)
           ms-appx://io.cordova.hellocordova/www/cordova.js:1143:5           Anonymous function()
           ms-appx://io.cordova.hellocordova/www/cordova.js:649:33           f()
           ms-appx://io.cordova.hellocordova/www/cordova.js:777:13           Channel.prototype.fire()
           ms-appx://io.cordova.hellocordova/www/cordova.js:1135:9           Anonymous function()
           ms-appx://io.cordova.hellocordova/www/cordova.js:1698:5           onScriptLoadingComplete(object, object)
```

**Comment by alsorokin** [comment]
Some more details:
This particular crash is only happening when building for windows 8.1 store/phone
If, for example, we run it like this:
`cordova run -- --appx=uap --archs=x64`
Then the app actually starts, but when we run the tests, another js exception is happening (but no crash). I've found the following messages in the `Microsoft-Windows-AppHost/ApplicationTracing` event log:
```
Exception calling native with command :: Engagement :: getStatus ::exception=ReferenceError: 'engagement' is undefined
```
```
SCRIPT5007 : Unable to get property 'pluginVersion' of undefined or null reference
```

**Comment by ogoguel** [comment]
If it happens only on Windows 8.1, sounds related to the issue of injecting dynamic content into an html page, cf.  https://github.com/Microsoft/winstore-jscompat

Try adding this cordova plugin to see if it helps 

`cordova plugin add https://github.com/vjrantal/cordova-plugin-winstore-jscompat`

**Comment by alsorokin** [comment]
Hey @ogoguel 
Thanks for the suggestion. Unfortunately it didn't help: after adding this plugin I got a crash with the same exception message in logs.

**Comment by ogoguel** [comment]
Got it : the plugin could not be loaded if the content page was located in a subdirectory (which was the case for the tests).

Try https://github.com/Azure/azure-mobile-engagement-cordova/pull/38  : finger crossed!

**Comment by alsorokin** [comment]
@ogoguel works like a charm, thanks!

**Comment by ogoguel** [comment]
Ouf! It was un unusual use case, but a use case anyway. 
Don't hesitate to post new issues to help us improving the plugin
Cheers
