### ISSUE TITLE
Android: Bug : all commands finished with success callback with incorrect endpoint

### ISSUE THREAD

**Issue by dolgof** [Azure/azure-mobile-engagement-cordova#40]
All commands return success callback and returns result "OK"
but in the device log i see:
E/engagement-test(12013): io.cordova.myappf0757c: **Invalid connection string, please do not alter the one you copied from portal, use it as is.**
I/engagement-test(12013): io.cordova.myappf0757c: AppInfo triggered: {"CDVAZME":"3.2.2"}

**Comment by ogoguel** [comment]
That's an issue with the current version of the Visual Studio Extension (TACO) that cannot properly pass the plugin arguments (cf. `plaftorm/android/android.json`)

A quick fix is to manually remove then add the plugin from the command line :
```
cordova plugin rm cordova-plugin-ms-azure-mobile-engagement
cordova plugin add cordova-plugin-ms-azure-mobile-engagement
```
