### ISSUE TITLE
iOS : Can't build on Cocoon

### ISSUE THREAD

**Issue by JiDW** [Azure/azure-mobile-engagement-cordova#41]
Hello,

First of all, it worked fine 1 month ago.
When I try to build my project with Cocoon I get the following error : 

COMPILER ERROR: 

Internal compiler error

CORDOVA LOG: 

diagnostics /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Objects-normal/armv7/AZMECordova.dia -c /workspace/platforms/ios/Celsius\ Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/AZMECordova.m -o /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Objects-normal/armv7/AZMECordova.o
CompileC /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Objects-normal/armv7/AZMECordova.o Celsius\ Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/AZMECordova.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /workspace/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/tools:/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-darwin/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Celsius\ Heroes-generated-files.hmap -I/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Celsius\ Heroes-own-target-headers.hmap -I/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Celsius\ Heroes-all-target-headers.hmap -iquote /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Celsius\ Heroes-project-headers.hmap -I/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/BuildProductsPath/Release-iphoneos/include -I/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/InstallationBuildProductsLocation/Applications/usr/local/lib/include -I/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/UninstalledProducts/include -I/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/include -I/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/BuildProductsPath/Release-iphoneos -I/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/DerivedSources/armv7 -I/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/DerivedSources -F/Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/BuildProductsPath/Release-iphoneos -FCelsius\ Heroes/Plugins/com.adjust.sdk -FCelsius\ Heroes/Plugins/cocoon-plugin-social-ios-facebook -FCelsius\ Heroes/Plugins/cocoon-plugin-application-android -FCelsius\ Heroes/Plugins/cocoon-plugin-ads-ios-chartboost -include /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/PrecompiledHeaders/Celsius\ Heroes-Prefix-fvnzrprzpuemphbxqjahhchknpoe/Celsius\ Heroes-Prefix.pch -MMD -MT dependencies -MF /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Objects-normal/armv7/AZMECordova.d --serialize-diagnostics /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Objects-normal/armv7/AZMECordova.dia -c /workspace/platforms/ios/Celsius\ Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/AZMECordova.m -o /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Objects-normal/armv7/AZMECordova.o[32m[2016-11-03 09:37:17.924] [INFO] IOSBuilder - [39mIn file included from /workspace/platforms/ios/Celsius Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/AZMECordova.m:11:
In file included from /workspace/platforms/ios/Celsius Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/AZMECordova.h:9:
In file included from /workspace/platforms/ios/Celsius Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/EngagementShared.h:7:
/workspace/platforms/ios/Celsius Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/EngagementAgent.h:6:9: fatal error: 'UserNotifications/UserNotifications.h' file not found
#import 
        ^
1 error generated.
In file included from /workspace/platforms/ios/Celsius Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/AZMECordova.m:11:
In file included from /workspace/platforms/ios/Celsius Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/AZMECordova.h:9:
In file included from /workspace/platforms/ios/Celsius Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/EngagementShared.h:7:
/workspace/platforms/ios/Celsius Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/EngagementAgent.h:6:9: fatal error: 'UserNotifications/UserNotifications.h' file not found
#import 
        ^
1 error generated.[32m[2016-11-03 09:37:17.925] [INFO] IOSBuilder - [39m
[31m[2016-11-03 09:37:18.082] [ERROR] IOSBuilder - [39m** ARCHIVE FAILED **

The following build commands failed:
** ARCHIVE FAILED **

The following build commands failed:[31m[2016-11-03 09:37:18.084] [ERROR] IOSBuilder - [39mCompileC /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Objects-normal/armv7/AZMECordova.o Celsius\ Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/AZMECordova.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
CompileC /Library/Developer/Xcode/DerivedData/Celsius_Heroes-dtemtmrezbgwpibtyemccfvqnexk/Build/Intermediates/ArchiveIntermediates/Celsius\ Heroes/IntermediateBuildFilesPath/Celsius\ Heroes.build/Release-iphoneos/Celsius\ Heroes.build/Objects-normal/armv7/AZMECordova.o Celsius\ Heroes/Plugins/cordova-plugin-ms-azure-mobile-engagement/AZMECordova.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)[36m[2016-11-03 09:37:18.242] [DEBUG] IOSBuilder - [39m[build] clean
[36m[2016-11-03 09:37:18.243] [DEBUG] IOSBuilder - [39m[build] remove keychain
security: SecKeychainDelete: The specified keychain could not be found.
[33m[2016-11-03 09:37:18.381] [WARN] IOSBuilder - [39mCommand failed: security delete-keychain '6B282E6F.keychain'
security: SecKeychainDelete: The specified keychain could not be found.

Regards.

**Comment by ogoguel** [comment]
Sounds like your the CocoonJS toolchain has not been updated to the latest version of XCode....

If you cannot have XCode being updated to version 8, please use a branch of the SDK prior to to the integration of the support for iOS 10
(cf.
https://github.com/Azure/azure-mobile-engagement-cordova/commit/4ba4ed586c2a91106f1cdea1ad62212d7e328b11)
