### ISSUE TITLE
AZME_ANDROID_REACH_ICON : Gradle Error

### ISSUE THREAD

**Issue by AlaeddineMessadi** [Azure/azure-mobile-engagement-cordova#42]
Like in the documentation:
The icon name is `myappicon.png`, the file is moved to `platforms/android/res/drawable` and I removed its extension `platforms/android/res/drawable/myappicon`.

when I try to build the project, Gradle refuse the file and throws and error : 
```
Error: platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeReleaseResources'.
> platforms/android/res/drawable/myappicon: Error: The file name must end with .xml or .png

```

**Comment by ogoguel** [comment]
There's some confusion about the extension removal : 
* the icon file should remain its extension
* the extension must be removed from the `AZME_ANDROID_REACH_ICON` variable.

In your case, it should be : 
* `platforms/android/res/drawable/myappicon.png` (with .png)
* `AZME_ANDROID_REACH_ICON="myappicon"` (without .png)

Will update the documentiation to clarify it
