### ISSUE TITLE
What does mean Native Notifications Enabled = false?

### ISSUE THREAD

**Issue by AlexSenchenko** [Azure/azure-mobile-engagement-cordova#44]
Hi
@macdonst @guperrot @ogoguel @kpiteira @piyushjo 

we are not recieving push notifications, while trying to troubleshoot it got following info:

What does it mean following?
Troubleshooting->Meta->Native Push Enabled->No

If we get status for Engagement:
[Engagement-Plugin] getStatus returned: {
    deviceId = 54bece5ea430ebbbad5748cf18d7c6fb;
    isEnabled = 1;
    nativeVersion = "4.0.1";
    notificationGranted = 1;
    pluginVersion = "3.2.3";
}

**Comment by ogoguel** [comment]
As the notification has been granted (cf. status), rhe application seems properly configured to receive the pushes. If "Native Push Enabled" is set to No, it likely means there's no push certificate/there's an invalid certificate registered in the azme portal.
If it still doe snot work, please attach the full log

**Comment by AlexSenchenko** [comment]
@ogoguel thanks for answering - we fixed it already.
