### ISSUE TITLE
Android: Session still is active after closing the app

### ISSUE THREAD

**Issue by greybax** [Azure/azure-mobile-engagement-cordova#52]
**Repro steps**:
1. Open app
2. Do some navigation by views (each times do `startActivity(name, extraInfos)`)
3. Close app (swipe from list view)

Session in Monitor still is active and stayed in it **~30minutes**, but it should be closed

**Comment by greybax** [comment]
sent PR https://github.com/Azure/azure-mobile-engagement-app-android/pull/8 in native SDK for fix it. After applying PR there hope that we can make appropriate changes in this plugin for fix issue.

**Comment by greybax** [comment]
**FYI:** On [WebApp Azure Engagement](https://docs.microsoft.com/en-us/azure/mobile-engagement/mobile-engagement-web-integrate-engagement) I've found follow:

> The Mobile Engagement server automatically ends an open session within three minutes after the application page is closed.
> 
> Alternatively, you can end a session manually by calling engagement.agent.endActivity. This sets the current user activity to 'Idle.' The session will end 10 seconds later unless a new call to engagement.agent.startActivity resumes the session.
> 
> You can configure the 10-second delay in the global engagement object, as follows:

```
engagement.sessionTimeout = 2000; // 2 seconds
// or
engagement.sessionTimeout = 0; // end the session as soon as endActivity is called
```

Android app engagement needs to this API too.

**Comment by ogoguel** [comment]
A cordova application is not impacted by this issue, as the plugin automatically sends an `EndActivity()` event when the application is being paused.

**Comment by greybax** [comment]
@ogoguel Yes if app is paused `endActivity()` event sends successfully. But I have repro steps where it doesn't work:
1. Open list app
2. Close app via swipe immediately as soon as list app was opened.

So in this case app doesn't set to `pause` mode and if app was closed session still alive >30minutes

**Comment by clpolet** [comment]
Swiping the app from the multitask menu kills it, in this case even the Android `OnDestroy` API may not be called. There is no reliable way to detect this scenario from the SDK side. Also the Web app SDK has a special treatment in our service due to the nature of the web sessions but this is not available to Android devices.
